# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoiceline_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ('-billable', 'work_type')},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('date', 'amount')},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
