# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20170816_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
