# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20170820_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ('-billable', 'work_type', '-start_date')},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date', 'amount')},
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice_sent_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 21, 19, 35, 23, 410960, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
