# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20170821_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice_sent_date',
            field=models.DateField(blank=True),
        ),
    ]
